### ISSUE TITLE
How can I get the UNLV dataset

### ISSUE THREAD

**Issue by Yuxiang1995** [hassan-mahmood/TIES_DataGeneration#4]
Hey,I met a problem that I can not find the UNLV dataset image from open source. Could you send me a link? Thx

**Comment by hassan-mahmood** [comment]
I have added link to UNLV dataset in ReadMe file.

**Comment by Yuxiang1995** [comment]
> I have added link to UNLV dataset in ReadMe file.

thanks a lot
